# Generated by Django 4.0.4 on 2022-05-24 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_created_task_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
    ]
